# Generated by Django 6.0.7 on 2026-08-27 21:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


"""Початкова міграція accounts (стиснуті 0001+0002+0003).

Три файли існували через циклічну залежність
`UserProfile.default_shipping_address` -> `orders.ShippingAddress` ->
`accounts.CustomUser`: Django не міг збудувати граф і розбивав accounts
навпіл. Поле прибрано (єдине джерело істини — `ShippingAddress.is_default`),
цикл зник, міграції стиснуто в одну.

Залежність від `orders` тут теж прибрана вручну: squashmigrations затягнув
її з 0002 за інерцією, хоча жодна операція нижче на orders не посилається.
"""


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_initial'), ('accounts', '0003_catalog_expansion')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_subscribed', models.BooleanField(default=False, help_text='Листи про нові аромати й закриті передпродажі', verbose_name='Підписка на розсилку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зареєстрований')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m', verbose_name='Аватар')),
                ('favourite_family', models.CharField(blank=True, choices=[('woody', 'Деревні'), ('floral', 'Квіткові'), ('amber', 'Амброві'), ('citrus', 'Цитрусові'), ('gourmand', 'Гурманські'), ('leather', 'Шкіра і тютюн'), ('aquatic', 'Акватичні')], help_text='За нею кабінет підбирає рекомендації', max_length=20, verbose_name='Улюблена ольфакторна родина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
