# Generated by Django 6.0.7 on 2026-08-27 21:41

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Країна')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)], verbose_name='Рік заснування')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('logo', models.ImageField(blank=True, help_text='JPG, JPEG, PNG, WEBP, до 5 МБ', null=True, upload_to='brands/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), shop.models.validate_image_size], verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('family', models.CharField(choices=[('citrus', 'Цитрусові'), ('floral', 'Квіткові'), ('woody', 'Деревні'), ('spicy', 'Спеції'), ('resin', 'Смоли'), ('gourmand', 'Гурманські'), ('green', 'Зелені'), ('aquatic', 'Акватичні'), ('animalic', 'Тваринні')], max_length=20, verbose_name='Родина')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Нота',
                'verbose_name_plural': 'Ноти',
                'ordering': ['family', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('top', 'Верхні'), ('heart', 'Серце'), ('base', 'База')], max_length=10, verbose_name='Шар')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок у шарі')),
            ],
            options={
                'verbose_name': 'Нота товару',
                'verbose_name_plural': 'Ноти товару',
                'ordering': ['layer', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Підтверджена покупка')),
                ('is_approved', models.BooleanField(default=False, help_text='Відгук зʼявиться на сайті лише після перевірки', verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'sort_order', 'id'], 'verbose_name': 'Зображення товару', 'verbose_name_plural': 'Зображення товарів'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_slug_76971b_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG, JPEG, PNG, WEBP, до 5 МБ', upload_to='categories/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), shop.models.validate_image_size], verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='На головній'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(blank=True, choices=[('edc', 'Eau de Cologne'), ('edt', 'Eau de Toilette'), ('edp', 'Eau de Parfum'), ('extrait', 'Extrait de Parfum'), ('oil', 'Олія')], max_length=10, verbose_name='Концентрація'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Країна виробництва'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, help_text='JPG, JPEG, PNG, WEBP, до 5 МБ', upload_to='products/covers/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), shop.models.validate_image_size], verbose_name='Головне фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Унісекс'), ('feminine', 'Жіночий'), ('masculine', 'Чоловічий')], default='unisex', max_length=10, verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Кураторський вибір'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='longevity_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48)], verbose_name='Стійкість, годин'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заповніть, щоб показати знижку', max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AddField(
            model_name='product',
            name='perfumer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Парфумер'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Два речення для картки в каталозі', max_length=300, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='sillage',
            field=models.CharField(blank=True, choices=[('intimate', 'Камерний'), ('moderate', 'Помірний'), ('strong', 'Сильний'), ('enormous', 'Дуже сильний')], max_length=10, verbose_name='Шлейф'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Переглядів'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Обʼєм, мл'),
        ),
        migrations.AddField(
            model_name='product',
            name='year_released',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)], verbose_name='Рік випуску'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Якщо не заповнити — підставиться назва товару', max_length=200, verbose_name='Альтернативний текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='JPG, JPEG, PNG, WEBP, до 5 МБ', upload_to='products/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), shop.models.validate_image_size], verbose_name='Зображення'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='one_main_image_per_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brand', verbose_name='Бренд'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['family'], name='shop_note_family_2da3bb_idx'),
        ),
        migrations.AddField(
            model_name='productnote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_notes', to='shop.note', verbose_name='Нота'),
        ),
        migrations.AddField(
            model_name='productnote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notes', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='products', through='shop.ProductNote', to='shop.note', verbose_name='Ноти'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'category'], name='shop_produc_is_avai_1aecc5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='shop_produc_is_feat_e938b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='shop_produc_price_3b79b5_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddConstraint(
            model_name='productnote',
            constraint=models.UniqueConstraint(fields=('product', 'note', 'layer'), name='unique_product_note_layer'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved'], name='shop_review_product_ae89ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='one_review_per_user_per_product'),
        ),
    ]
