# Generated by Django 6.0.7 on 2026-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_tighten_brand_and_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='source_query',
            field=models.CharField(blank=True, max_length=250, verbose_name='Пошуковий запит'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Джерело'),
        ),
    ]
