# Generated by Django 6.0.7 on 2026-09-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='Хеш джерела'),
        ),
    ]
