# Generated by Django 6.0.7 on 2026-07-27 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер замовлення')),
                ('shipping_full_name', models.CharField(max_length=200, verbose_name='ПІБ отримувача')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('shipping_country', models.CharField(max_length=100, verbose_name='Країна')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Місто')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='Поштовий індекс')),
                ('shipping_address_line1', models.CharField(max_length=250, verbose_name='Адреса (рядок 1)')),
                ('shipping_address_line2', models.CharField(blank=True, max_length=250, verbose_name='Адреса (рядок 2)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума замовлення')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівкою при отриманні'), ('card', 'Оплата карткою онлайн'), ('bank', 'Банківський переказ')], default='cash', max_length=20, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Назва товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор зміни')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусів',
                'verbose_name_plural': 'Історія статусів',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('country', models.CharField(default='Україна', max_length=100, verbose_name='Країна')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Поштовий індекс')),
                ('address_line1', models.CharField(max_length=250, verbose_name='Адреса (рядок 1)')),
                ('address_line2', models.CharField(blank=True, max_length=250, verbose_name='Адреса (рядок 2)')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Адреса доставки',
                'verbose_name_plural': 'Адреси доставки',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
