# Generated by Django 6.0.7 on 2026-08-31 16:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Вартість')),
                ('free_from', models.DecimalField(blank=True, decimal_places=2, help_text='Порожньо — доставка платна завжди', max_digits=10, null=True, verbose_name='Безкоштовно від суми')),
                ('estimated_days', models.PositiveSmallIntegerField(default=2, verbose_name='Днів у дорозі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Спосіб доставки',
                'verbose_name_plural': 'Способи доставки',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Код промокоду'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Доставка (знімок назви)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Вартість доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Знижка'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Очікувана доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email гостя'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон гостя'),
        ),
        migrations.AddField(
            model_name='order',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сума товарів'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Разом до сплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Зберігається у верхньому регістрі', max_length=32, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Опис')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток від суми'), ('fixed', 'Фіксована сума')], default='percent', max_length=10, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Для відсоткової знижки — від 1 до 100', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Розмір знижки')),
                ('valid_from', models.DateTimeField(verbose_name='Діє з')),
                ('valid_to', models.DateTimeField(verbose_name='Діє до')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 — без обмеження', verbose_name='Ліміт використань')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано разів')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Мінімальна сума замовлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='orders_coup_code_ca5871_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverymethod', verbose_name='Спосіб доставки'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('guest_email', ''), _negated=True), _connector='OR'), name='order_has_customer'),
        ),
    ]
